// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtH6RCK52bn4RWBU66kCOHFOB93Sh4rAE',
    appId: '1:67274106072:web:e54c470db949ae9579e3ad',
    messagingSenderId: '67274106072',
    projectId: 'laporbook-3a80c',
    authDomain: 'laporbook-3a80c.firebaseapp.com',
    storageBucket: 'laporbook-3a80c.appspot.com',
    measurementId: 'G-S6RSFK22JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgTpM2g9x7clDMAZocUdm0fIRUG_bBtvQ',
    appId: '1:67274106072:android:3ba97ac1020d242279e3ad',
    messagingSenderId: '67274106072',
    projectId: 'laporbook-3a80c',
    storageBucket: 'laporbook-3a80c.appspot.com',
  );
}
